CREATE DATABASE SENAI_HROADS_MANHA

USE SENAI_HROADS_MANHA

CREATE TABLE TIPOS_HABILIDADES (
	ID INT IDENTITY PRIMARY KEY
	, NOME VARCHAR(30) NOT NULL
);

CREATE TABLE HABILIDADES (
	ID INT IDENTITY PRIMARY KEY
	, NOME VARCHAR(60) NOT NULL
	, ID_HABILIDADE INT FOREIGN KEY REFERENCES TIPOS_HABILIDADES(ID)
);

CREATE TABLE CLASSES (
	ID INT IDENTITY PRIMARY KEY
	, NOME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE PERSONAGEM (
	ID INT IDENTITY PRIMARY KEY
	, NOME VARCHAR(50) NOT NULL UNIQUE
	, ID_CLASSE INT FOREIGN KEY REFERENCES CLASSES(ID)
	, LVL INT NOT NULL 
	, MAX_VIDA INT NOT NULL
	, MAX_MANA INT NOT NULL
	, DATA_CRIACAO DATETIME 
	, DATA_ATUALIZACAO DATETIME
);

CREATE TABLE CLASSES_HABILIDADES (
	ID_CLASSES INT FOREIGN KEY REFERENCES CLASSES(ID)
	, ID_HABILIDADES INT FOREIGN KEY REFERENCES HABILIDADES(ID)
);