USE SENAI_HROADS_MANHA

SELECT * FROM PERSONAGEM

SELECT * FROM CLASSES 

SELECT NOME FROM CLASSES

SELECT * FROM HABILIDADES 
SELECT * FROM TIPOS_HABILIDADES

SELECT COUNT(*) AS QUANTIDADE FROM HABILIDADES

SELECT * FROM HABILIDADES ORDER BY ID ASC

SELECT * FROM TIPOS_HABILIDADES

SELECT HABILIDADES.NOME 
FROM HABILIDADES
INNER JOIN TIPOS_HABILIDADES ON TIPOS_HABILIDADES.ID = HABILIDADES.ID_HABILIDADE

